$(function(){
  var currencies = [
    { value: "Accommodation warden" },
    { value: "Accounting technician" },
    { value: "Acoustics consultant" },
    { value: "Actor" },
    { value: "Actuary" },
    { value: "Acupuncturist" },
    { value: "Admin assistant" },
    { value: "Advertising account executive" },
    { value: "Advertising account planner" },
    { value: "Advertising art director" },
    { value: "Advertising copywriter" },
    { value: "Advertising media buyer" },
    { value: "Advertising media planner" },
    { value: "Aerospace engineer" },
    { value: "Aerospace engineering technician" },
    { value: "Agricultural contractor" },
    { value: "Agricultural engineer" },
    { value: "Agricultural engineering technician" },
    { value: "Agricultural inspector" },
    { value: "Air cabin crew" },
    { value: "Air traffic controller" },
    { value: "Airline customer service agent" },
    { value: "Airline pilot" },
    { value: "Airport baggage handler" },
    { value: "Airport information assistant" },
    { value: "Alexander Technique teacher" },
    { value: "Ambulance care assistant" },
    { value: "Anaesthetist" },
    { value: "Analytical textile technologist" },
    { value: "Anatomical pathology technician" },
    { value: "Animal care worker" },
    { value: "Animal technician" },
    { value: "Animator" },
    { value: "Antique Dealer" },
    { value: "Arboricultural officer" },
    { value: "Archaeologist" },
    { value: "Architect" },
    { value: "Architectural technician or technologist" },
    { value: "Architectural technologist" },
    { value: "Archivist" },
    { value: "Army officer" },
    { value: "Aromatherapist" },
    { value: "Art editor" },
    { value: "Art gallery curator" },
    { value: "Art therapist" },
    { value: "Art valuer" },
    { value: "Arts administrator" },
    { value: "Assembler" },
    { value: "Assistance dog trainer" },
    { value: "Assistant immigration officer" },
    { value: "Astronaut" },
    { value: "Astronomer" },
    { value: "Audio visual technician" },
    { value: "Audiologist" },
    { value: "Auditor" },
    { value: "Auto electrician" },
    { value: "Automotive engineer" },
    { value: "Bailiff" },
    { value: "Baker" },
    { value: "Bank manager" },
    { value: "Banking customer service adviser" },
    { value: "Bar person" },
    { value: "Barista" },
    { value: "Barrister" },
    { value: "Barrister's clerk" },
    { value: "Beauty consultant" },
    { value: "Beauty therapist" },
    { value: "Beekeeper" },
    { value: "Betting shop cashier" },
    { value: "Bid writer" },
    { value: "Bilingual secretary" },
    { value: "Biochemist" },
    { value: "Biologist" },
    { value: "Biomedical scientist" },
    { value: "Biotechnologist" },
    { value: "Blacksmith" },
    { value: "Boat builder" },
    { value: "Body piercer" },
    { value: "Bodyguard" },
    { value: "Bomb disposal technician" },
    { value: "Bookbinder" },
    { value: "Bookkeeper" },
    { value: "Bookmaker" },
    { value: "Bookseller" },
    { value: "Border force officer" },
    { value: "Botanist" },
    { value: "Bottler" },
    { value: "Brewery worker" },
    { value: "Bricklayer" },
    { value: "British sign language interpreter" },
    { value: "Broadcast engineer" },
    { value: "Broadcast journalist" },
    { value: "Builders' merchant" },
    { value: "Building control officer" },
    { value: "Building services engineer" },
    { value: "Building site inspector" },
    { value: "Building surveyor" },
    { value: "Building technician" },
    { value: "Bus or coach driver" },
    { value: "Business adviser" },
    { value: "Business analyst" },
    { value: "Business development manager" },
    { value: "Business project manager" },
    { value: "Butcher" },
    { value: "Butler" },
    { value: "CAD technician" },
    { value: "Cake decorator" },
    { value: "Call centre operator" },
    { value: "Car fleet manager" },
    { value: "Car manufacturing worker" },
    { value: "Car rental agent" },
    { value: "Car salesperson" },
    { value: "Car valet" },
    { value: "Care escort" },
    { value: "Care home advocate" },
    { value: "Care home manager" },
    { value: "Care worker" },
    { value: "Careers adviser" },
    { value: "Caretaker" },
    { value: "Carpenter" },
    { value: "Carpet fitter and floor layer" },
    { value: "Cartographer" },
    { value: "Catering manager" },
    { value: "Cavity insulation installer" },
    { value: "Ceiling fixer" },
    { value: "Cellar technician" },
    { value: "Cement maker" },
    { value: "Cemetery worker" },
    { value: "Ceramics designer-maker" },
    { value: "Charity director" },
    { value: "Charity fundraiser" },
    { value: "Chauffeur" },
    { value: "Checkout operator" },
    { value: "Chef" },
    { value: "Chemical engineer" },
    { value: "Chemical engineering technician" },
    { value: "Chemical plant process operator" },
    { value: "Chief executive" },
    { value: "Chief inspector" },
    { value: "Childminder" },
    { value: "Children's nurse" },
    { value: "Chimney sweep" },
    { value: "Chiropractor" },
    { value: "Choreographer" },
    { value: "Cinema or theatre attendant" },
    { value: "Cinema projectionist" },
    { value: "Circus performer" },
    { value: "Civil enforcement officer" },
    { value: "Civil engineer" },
    { value: "Civil engineering technician" },
    { value: "Civil Service administrative officer" },
    { value: "Classical musician" },
    { value: "Cleaner" },
    { value: "Clinical engineer" },
    { value: "Clinical psychologist" },
    { value: "Clinical scientist" },
    { value: "Clothing alteration hand" },
    { value: "Clothing presser" },
    { value: "CNC machinist" },
    { value: "Coal miner" },
    { value: "Coastguard" },
    { value: "Cognitive behavioural therapist" },
    { value: "Colon hydrotherapist" },
    { value: "Colour therapist" },
    { value: "Commercial energy assessor" },
    { value: "Commissioning editor" },
    { value: "Community arts worker" },
    { value: "Community development worker" },
    { value: "Community education coordinator" },
    { value: "Community matron" },
    { value: "Community transport driver" },
    { value: "Community transport operations manager" },
    { value: "Company secretary" },
    { value: "Computer games developer" },
    { value: "Computer games tester" },
    { value: "Conference and exhibition manager" },
    { value: "Conservator" },
    { value: "Construction contracts manager" },
    { value: "Construction labourer" },
    { value: "Construction manager" },
    { value: "Construction plant mechanic" },
    { value: "Construction plant operator" },
    { value: "Construction site supervisor" },
    { value: "Consumer scientist" },
    { value: "Copy Editor" },
    { value: "Coroner" },
    { value: "Costume designer" },
    { value: "Counsellor" },
    { value: "Counter service assistant" },
    { value: "Countryside officer" },
    { value: "Countryside ranger" },
    { value: "Courier" },
    { value: "Court administrative assistant" },
    { value: "Court legal adviser" },
    { value: "Court usher" },
    { value: "Crane driver" },
    { value: "Credit agent" },
    { value: "Credit controller" },
    { value: "Credit manager" },
    { value: "Crematorium technician" },
    { value: "Criminal intelligence analyst" },
    { value: "Critical care technologist" },
    { value: "Croupier" },
    { value: "Crown prosecutor" },
    { value: "Cruise ship steward" },
    { value: "Customer service assistant" },
    { value: "Customer services manager" },
    { value: "Customs officer" },
    { value: "Cycle mechanic" },
    { value: "Cycling coach" },
    { value: "Dance movement psychotherapist" },
    { value: "Dance teacher" },
    { value: "Dancer" },
    { value: "Data analyst-statistician" },
    { value: "Data entry clerk" },
    { value: "Database administrator" },
    { value: "Delivery van driver" },
    { value: "Demolition operative" },
    { value: "Dental hygienist" },
    { value: "Dental nurse" },
    { value: "Dental technician" },
    { value: "Dental therapist" },
    { value: "Dentist" },
    { value: "Design and development engineer" },
    { value: "Dietitian" },
    { value: "Digital marketing officer" },
    { value: "Diplomatic service officer" },
    { value: "Director of photography" },
    { value: "Dispensing optician" },
    { value: "District nurse" },
    { value: "Diver" },
    { value: "DJ" },
    { value: "Dog groomer" },
    { value: "Dog handler" },
    { value: "Domestic appliance service engineer" },
    { value: "Domestic energy assessor" },
    { value: "Door supervisor" },
    { value: "Dramatherapist" },
    { value: "Dressmaker" },
    { value: "Driving instructor" },
    { value: "Drug and alcohol worker" },
    { value: "Dry cleaner" },
    { value: "Dry liner" },
    { value: "Early years teacher" },
    { value: "Ecologist" },
    { value: "Economic development officer" },
    { value: "Economist" },
    { value: "Editorial assistant" },
    { value: "Education technician" },
    { value: "Education welfare officer" },
    { value: "EFL teacher" },
    { value: "E-learning developer" },
    { value: "Electrical engineer" },
    { value: "Electrical engineering technician" },
    { value: "Electrician" },
    { value: "Electricity distribution worker" },
    { value: "Electricity generation worker" },
    { value: "Electronics engineer" },
    { value: "Electronics engineering technician" },
    { value: "Electroplater" },
    { value: "Embalmer" },
    { value: "Emergency care assistant" },
    { value: "Emergency medical dispatcher" },
    { value: "Energy engineer" },
    { value: "Engineering construction craftworker" },
    { value: "Engineering construction technician" },
    { value: "Engineering craft machinist" },
    { value: "Engineering maintenance technician" },
    { value: "Engineering operative" },
    { value: "Entertainer" },
    { value: "Entertainment agent" },
    { value: "Environmental consultant" },
    { value: "Environmental health officer" },
    { value: "Equalities officer" },
    { value: "Ergonomist" },
    { value: "Estate agent" },
    { value: "Estates officer" },
    { value: "Estimator" },
    { value: "European union official" },
    { value: "Events manager" },
    { value: "Exhibition designer" },
    { value: "Facilities manager" },
    { value: "Fairground worker" },
    { value: "Family mediator" },
    { value: "Family support worker" },
    { value: "Farm secretary" },
    { value: "Farm worker" },
    { value: "Farmer" },
    { value: "Farrier" },
    { value: "Fashion design assistant" },
    { value: "Fashion designer" },
    { value: "Fashion model" },
    { value: "Fence installer" },
    { value: "Finance officer" },
    { value: "Financial adviser" },
    { value: "Financial services customer adviser" },
    { value: "Fine artist" },
    { value: "Fingerprint officer" },
    { value: "Firefighter" },
    { value: "Fish farmer" },
    { value: "Fish frier" },
    { value: "Fishing boat deckhand" },
    { value: "Fishing vessel skipper" },
    { value: "Fishmonger" },
    { value: "Fitness instructor" },
    { value: "Florist" },
    { value: "Food factory worker" },
    { value: "Food manufacturing inspector" },
    { value: "Food packaging operative" },
    { value: "Food scientist" },
    { value: "Football coach" },
    { value: "Football referee" },
    { value: "Footballer" },
    { value: "Footwear designer" },
    { value: "Footwear manufacturing operative" },
    { value: "Forensic computer analyst" },
    { value: "Forensic psychologist" },
    { value: "Forensic scientist" },
    { value: "Forest officer" },
    { value: "Forestry worker" },
    { value: "Forklift driver" },
    { value: "Forklift truck engineer" },
    { value: "Foster carer" },
    { value: "Foundry mould maker" },
    { value: "Foundry patternmaker" },
    { value: "Foundry process operator" },
    { value: "Franchise owner" },
    { value: "Freight forwarder" },
    { value: "French polisher" },
    { value: "Funeral director" },
    { value: "Furniture designer" },
    { value: "Furniture maker" },
    { value: "Furniture restorer" },
    { value: "Further education lecturer" },
    { value: "Gamekeeper" },
    { value: "Garage manager" },
    { value: "Garden nursery assistant" },
    { value: "Gardener" },
    { value: "Garment technologist" },
    { value: "Gas mains layer" },
    { value: "Gas service technician" },
    { value: "General practice surveyor" },
    { value: "Geneticist" },
    { value: "Geoscientist" },
    { value: "Geotechnician" },
    { value: "Glass engraver" },
    { value: "Glassmaker" },
    { value: "Glazier" },
    { value: "GP" },
    { value: "GP practice manager" },
    { value: "Grants officer" },
    { value: "Graphic designer" },
    { value: "Groundsperson" },
    { value: "Hairdresser" },
    { value: "Hairdressing salon manager" },
    { value: "Handyperson" },
    { value: "Hat designer" },
    { value: "Head chef" },
    { value: "Head of IT (IT director)" },
    { value: "Headteacher" },
    { value: "Health and safety adviser" },
    { value: "Health play specialist" },
    { value: "Health promotion specialist" },
    { value: "Health records clerk" },
    { value: "Health service manager" },
    { value: "Health trainer" },
    { value: "Health visitor" },
    { value: "Healthcare assistant" },
    { value: "Healthcare science assistant" },
    { value: "Heat treatment operator" },
    { value: "Heating and ventilation engineer" },
    { value: "Helicopter engineer" },
    { value: "Helicopter pilot" },
    { value: "Her Majesty’s Inspector and regulatory inspector" },
    { value: "Higher education lecturer" },
    { value: "Highways cleaner" },
    { value: "Homeopath" },
    { value: "Horse groom" },
    { value: "Horse riding instructor" },
    { value: "Horticultural manager" },
    { value: "Horticultural therapist" },
    { value: "Horticultural worker" },
    { value: "Hospital doctor" },
    { value: "Hospital porter" },
    { value: "Hotel manager" },
    { value: "Hotel porter" },
    { value: "Hotel receptionist" },
    { value: "Hotel reservations assistant" },
    { value: "Hotel room attendant" },
    { value: "Housekeeper" },
    { value: "Housing officer" },
    { value: "Housing policy officer" },
    { value: "Human resources assistant" },
    { value: "Human resources manager" },
    { value: "Human resources officer" },
    { value: "Hypnotherapist" },
    { value: "Illustrator" },
    { value: "Image consultant" },
    { value: "Immigration adviser (non-government)" },
    { value: "Immigration officer" },
    { value: "Import-export clerk" },
    { value: "Indexer" },
    { value: "Industrial cleaner" },
    { value: "Information scientist" },
    { value: "Insurance account manager" },
    { value: "Insurance broker" },
    { value: "Insurance claims handler" },
    { value: "Insurance claims manager" },
    { value: "Insurance loss adjuster" },
    { value: "Insurance risk surveyor" },
    { value: "Insurance technician" },
    { value: "Insurance underwriter" },
    { value: "Interior designer" },
    { value: "Interpreter" },
    { value: "Investment analyst" },
    { value: "Iron and steel mill supervisor" },
    { value: "IT project manager" },
    { value: "IT security coordinator" },
    { value: "IT service engineer" },
    { value: "IT support technician" },
    { value: "IT trainer" },
    { value: "Jewellery designer-maker" },
    { value: "Jockey" },
    { value: "Kennel worker" },
    { value: "Kiln attendant" },
    { value: "Kitchen and bathroom fitter" },
    { value: "Kitchen assistant" },
    { value: "Kitchen porter" },
    { value: "Knitter" },
    { value: "Laboratory technician" },
    { value: "Land and property valuer and auctioneer" },
    { value: "Land surveyor" },
    { value: "Landscape architect" },
    { value: "Landscaper" },
    { value: "Large goods vehicle driver" },
    { value: "Laundry worker" },
    { value: "Leakage operative" },
    { value: "Learning disability nurse" },
    { value: "Learning mentor" },
    { value: "Leather craftworker" },
    { value: "Leather technologist" },
    { value: "Legal executive" },
    { value: "Legal secretary" },
    { value: "Leisure centre assistant" },
    { value: "Leisure centre manager" },
    { value: "Letting agent" },
    { value: "Librarian" },
    { value: "Library assistant" },
    { value: "Licensed conveyancer" },
    { value: "Life coach" },
    { value: "Lifeguard" },
    { value: "Lift engineer" },
    { value: "Light industry assembler" },
    { value: "Lighting technician" },
    { value: "Live sound engineer" },
    { value: "Local government administrative assistant" },
    { value: "Local government officer" },
    { value: "Local government revenues officer" },
    { value: "Lock keeper" },
    { value: "Locksmith" },
    { value: "Machine presser" },
    { value: "Machine printer" },
    { value: "Magazine journalist" },
    { value: "Maintenance fitter" },
    { value: "Make-up artist" },
    { value: "Management accountant" },
    { value: "Management consultant" },
    { value: "Manufacturing supervisor" },
    { value: "Manufacturing systems engineer" },
    { value: "Marine engineer" },
    { value: "Marine engineering technician" },
    { value: "Market research data analyst" },
    { value: "Market research executive" },
    { value: "Market researcher" },
    { value: "Market trader" },
    { value: "Marketing director" },
    { value: "Marketing executive" },
    { value: "Marketing manager" },
    { value: "Martial arts instructor" },
    { value: "Massage therapist" },
    { value: "Materials engineer" },
    { value: "Materials technician" },
    { value: "Maternity support worker" },
    { value: "Measurement and control engineer" },
    { value: "Measurement and control technician" },
    { value: "Meat hygiene inspector" },
    { value: "Meat process worker" },
    { value: "Mechanical engineer" },
    { value: "Mechanical engineering technician" },
    { value: "Media researcher" },
    { value: "Medical herbalist" },
    { value: "Medical illustrator" },
    { value: "Medical physicist" },
    { value: "Medical sales representative" },
    { value: "Medical secretary" },
    { value: "Mental health nurse" },
    { value: "Merchant Navy deck officer" },
    { value: "Merchant Navy engineering officer" },
    { value: "Merchant Navy rating" },
    { value: "Meteorologist" },
    { value: "Microbiologist" },
    { value: "Midwife" },
    { value: "Minerals surveyor" },
    { value: "Model maker" },
    { value: "Money adviser" },
    { value: "Montessori teacher" },
    { value: "Mortgage adviser" },
    { value: "Motor mechanic" },
    { value: "Motor vehicle breakdown engineer" },
    { value: "Motor vehicle fitter" },
    { value: "Motor vehicle parts person" },
    { value: "Motorsport engineer" },
    { value: "MP" },
    { value: "Museum assistant" },
    { value: "Museum curator" },
    { value: "Music promotions manager" },
    { value: "Music teacher" },
    { value: "Music therapist" },
    { value: "Musical instrument maker and repairer" },
    { value: "Nail technician" },
    { value: "Nanny" },
    { value: "Nanotechnologist" },
    { value: "Naturopath" },
    { value: "Naval architect" },
    { value: "Neighbourhood warden" },
    { value: "Network engineer" },
    { value: "Network manager" },
    { value: "Newspaper journalist" },
    { value: "Newspaper or magazine editor" },
    { value: "Non-destructive testing technician" },
    { value: "Nuclear engineer" },
    { value: "Nurse" },
    { value: "Nursery manager" },
    { value: "Nursery worker" },
    { value: "Nutritional therapist" },
    { value: "Nutritionist" },
    { value: "Occupational health nurse" },
    { value: "Occupational therapist" },
    { value: "Occupational therapy support worker" },
    { value: "Oceanographer" },
    { value: "Office equipment service technician" },
    { value: "Office manager" },
    { value: "Offshore drilling worker" },
    { value: "Oil and gas operations manager" },
    { value: "Online tutor" },
    { value: "Operating department practitioner" },
    { value: "Operational researcher" },
    { value: "Optometrist" },
    { value: "Order picker" },
    { value: "Ornithologist" },
    { value: "Orthoptist" },
    { value: "Osteopath" },
    { value: "Outdoor activities instructor" },
    { value: "Packaging technologist" },
    { value: "Packer" },
    { value: "Paint sprayer" },
    { value: "Painter and decorator" },
    { value: "Palaeontologist" },
    { value: "Palliative care assistant" },
    { value: "Paper maker" },
    { value: "Paper technologist" },
    { value: "Paralegal" },
    { value: "Paramedic" },
    { value: "Patent attorney" },
    { value: "Pathologist" },
    { value: "Patient advice and liaison service officer" },
    { value: "Patient transport service controller" },
    { value: "Pattern cutter" },
    { value: "Pattern grader" },
    { value: "Payroll administrator" },
    { value: "Payroll manager" },
    { value: "PE teacher" },
    { value: "Pensions administrator" },
    { value: "Pensions adviser" },
    { value: "Pensions manager" },
    { value: "Personal assistant" },
    { value: "Personal shopper" },
    { value: "Personal trainer" },
    { value: "Pest control technician" },
    { value: "Pet behaviour counsellor" },
    { value: "Pet shop assistant" },
    { value: "Petrol station sales assistant" },
    { value: "Pharmacist" },
    { value: "Pharmacologist" },
    { value: "Pharmacy assistant" },
    { value: "Pharmacy technician" },
    { value: "Phlebotomist" },
    { value: "Photographer" },
    { value: "Photographic stylist" },
    { value: "Photographic technician" },
    { value: "Physicist" },
    { value: "Physiotherapist" },
    { value: "Physiotherapy assistant" },
    { value: "Picture framer" },
    { value: "Pilates teacher" },
    { value: "Pipe fitter" },
    { value: "Planning and development surveyor" },
    { value: "Plasterer" },
    { value: "Plastics process worker" },
    { value: "Play therapist" },
    { value: "Playworker" },
    { value: "Plumber" },
    { value: "Podiatrist" },
    { value: "Podiatry assistant" },
    { value: "Police community support officer" },
    { value: "Police officer" },
    { value: "Pop musician" },
    { value: "Port operative" },
    { value: "Portage home visitor" },
    { value: "Post office customer service assistant" },
    { value: "Postman or postwoman" },
    { value: "Practice nurse" },
    { value: "Pre-press operator" },
    { value: "Primary care graduate mental health worker" },
    { value: "Primary school teacher" },
    { value: "Printing administrator" },
    { value: "Printing assistant" },
    { value: "Prison governor" },
    { value: "Prison instructor" },
    { value: "Prison officer" },
    { value: "Private investigator" },
    { value: "Private practice accountant" },
    { value: "Probation officer" },
    { value: "Probation services officer" },
    { value: "Product designer" },
    { value: "Production manager (manufacturing)" },
    { value: "Production worker (manufacturing)" },
    { value: "Proofreader" },
    { value: "Prop maker" },
    { value: "Prosthetist-orthotist" },
    { value: "Psychiatrist" },
    { value: "Psychologist" },
    { value: "Psychotherapist" },
    { value: "Public finance accountant" },
    { value: "Public relations director" },
    { value: "Public relations officer" },
    { value: "Publican" },
    { value: "Purchasing manager" },
    { value: "QCF assessor" },
    { value: "Quality assurance manager" },
    { value: "Quality control assistant" },
    { value: "Quantity surveyor" },
    { value: "Quarry engineer" },
    { value: "Quarry worker" },
    { value: "Racehorse trainer" },
    { value: "Radio broadcast assistant" },
    { value: "Radiographer" },
    { value: "Radiography assistant" },
    { value: "RAF airman or woman" },
    { value: "RAF non-commissioned aircrew" },
    { value: "RAF officer" },
    { value: "Rail engineering technician" },
    { value: "Rail track maintenance worker" },
    { value: "Railway signaller" },
    { value: "Receptionist" },
    { value: "Recruitment consultant" },
    { value: "Recycled metals worker" },
    { value: "Recycling officer" },
    { value: "Recycling operative" },
    { value: "Reflexologist" },
    { value: "Refrigeration and air-conditioning installer" },
    { value: "Refuse collector" },
    { value: "Registrar of births, deaths, marriages and civil partnerships" },
    { value: "Reiki healer" },
    { value: "Religious leader" },
    { value: "Removals worker" },
    { value: "Reprographic assistant" },
    { value: "Research and development manager" },
    { value: "Research scientist" },
    { value: "Residential support worker" },
    { value: "Resort representative" },
    { value: "Restaurant manager" },
    { value: "Retail buyer" },
    { value: "Retail jeweller" },
    { value: "Retail manager" },
    { value: "Retail merchandiser" },
    { value: "Riding holiday centre manager" },
    { value: "Riding holiday leader" },
    { value: "Road haulage load planner" },
    { value: "Road traffic accident investigator" },
    { value: "Road transport manager" },
    { value: "Road worker" },
    { value: "Roadie" },
    { value: "Roofer" },
    { value: "Roofing labourer" },
    { value: "Roundsperson" },
    { value: "Roustabout" },
    { value: "Royal Marines commando" },
    { value: "Royal Marines officer" },
    { value: "Royal Navy officer" },
    { value: "Royal Navy rating" },
    { value: "RSPCA inspector" },
    { value: "Rubber process worker" },
    { value: "Rural surveyor" },
    { value: "Sailing instructor" },
    { value: "Sales administrator" },
    { value: "Sales assistant" },
    { value: "Sales manager" },
    { value: "Sales promotion executive" },
    { value: "Sales representative" },
    { value: "Sales supervisor" },
    { value: "Sample machinist" },
    { value: "Satellite engineer" },
    { value: "Scaffolder" },
    { value: "Scenes of crime officer" },
    { value: "School business manager" },
    { value: "School crossing patrol" },
    { value: "School lunchtime supervisor" },
    { value: "School matron" },
    { value: "School nurse" },
    { value: "School secretary" },
    { value: "Scrap metal worker" },
    { value: "Screenwriter" },
    { value: "Secondary school teacher" },
    { value: "Secretary" },
    { value: "Security officer" },
    { value: "Security service personnel" },
    { value: "Security systems installer" },
    { value: "Senior care worker" },
    { value: "Set designer" },
    { value: "Sewing machinist" },
    { value: "Sexual health adviser" },
    { value: "Sheet metal worker" },
    { value: "Shelf filler" },
    { value: "Shoe repairer" },
    { value: "Shopfitter" },
    { value: "Shopkeeper" },
    { value: "Signalling technician" },
    { value: "Signmaker" },
    { value: "Signwriter" },
    { value: "Singing teacher" },
    { value: "Skills for life teacher" },
    { value: "Smart meter installer" },
    { value: "Social media manager" },
    { value: "Social services manager" },
    { value: "Social work assistant" },
    { value: "Social worker" },
    { value: "Software developer" },
    { value: "Soldier" },
    { value: "Solicitor" },
    { value: "Special educational needs (SEN) teacher" },
    { value: "Special educational needs (SEN) teaching assistant" },
    { value: "Speech and language therapist" },
    { value: "Speech and language therapy assistant" },
    { value: "Sport and exercise psychologist" },
    { value: "Sports agent" },
    { value: "Sports club secretary" },
    { value: "Sports coach" },
    { value: "Sports commentator" },
    { value: "Sports development officer" },
    { value: "Sports physiotherapist" },
    { value: "Sports professional" },
    { value: "Sports scientist" },
    { value: "Stage manager" },
    { value: "Stagehand" },
    { value: "Steel erector" },
    { value: "Steel fixer" },
    { value: "Steeplejack" },
    { value: "Sterile services technician" },
    { value: "Stock control assistant" },
    { value: "Stockbroker" },
    { value: "Stonemason" },
    { value: "Store demonstrator" },
    { value: "Store detective" },
    { value: "Street food trader" },
    { value: "Structural engineer" },
    { value: "Studio sound engineer" },
    { value: "Stunt performer" },
    { value: "Sub-editor" },
    { value: "Substance misuse outreach worker" },
    { value: "Supervisor" },
    { value: "Supply chain manager" },
    { value: "Surgeon" },
    { value: "Swimming pool technician" },
    { value: "Swimming teacher" },
    { value: "Systems analyst" },
    { value: "Tailor" },
    { value: "Tanker driver" },
    { value: "Tattooist" },
    { value: "Tax adviser" },
    { value: "Tax inspector" },
    { value: "Taxi driver" },
    { value: "Teaching assistant" },
    { value: "Technical architect" },
    { value: "Technical author" },
    { value: "Technical brewer" },
    { value: "Technical surveyor" },
    { value: "Technical textiles designer" },
    { value: "Telecoms engineer" },
    { value: "Telephonist" },
    { value: "Telesales executive" },
    { value: "Textile designer" },
    { value: "Textile dyeing technician" },
    { value: "Textile machinery technician" },
    { value: "Textile operative" },
    { value: "Textile spinner" },
    { value: "Textile technologist" },
    { value: "Textiles production manager" },
    { value: "Thatcher" },
    { value: "Thermal insulation engineer" },
    { value: "Tiler" },
    { value: "Timber yard worker" },
    { value: "Toolmaker" },
    { value: "Tour manager" },
    { value: "Tourist guide" },
    { value: "Tourist information centre assistant" },
    { value: "Town planner" },
    { value: "Town planning assistant" },
    { value: "Tractor driver" },
    { value: "Trade mark attorney" },
    { value: "Trade union official" },
    { value: "Trading standards officer" },
    { value: "Train conductor" },
    { value: "Train driver" },
    { value: "Train station staff" },
    { value: "Training manager" },
    { value: "Training officer" },
    { value: "Tram driver" },
    { value: "Translator" },
    { value: "Transport planner" },
    { value: "Travel agency manager" },
    { value: "Travel agent" },
    { value: "Tree surgeon" },
    { value: "TV or film assistant director" },
    { value: "TV or film camera operator" },
    { value: "TV or film director" },
    { value: "TV or film producer" },
    { value: "TV or film production assistant" },
    { value: "TV or film production manager" },
    { value: "TV or film production runner" },
    { value: "TV or film sound technician" },
    { value: "TV presenter" },
    { value: "Typist" },
    { value: "Upholsterer" },
    { value: "Vehicle body repairer" },
    { value: "Vending machine operator" },
    { value: "Vet" },
    { value: "Veterinary nurse" },
    { value: "Veterinary physiotherapist" },
    { value: "Victim care officer" },
    { value: "Video editor" },
    { value: "Visitor attraction general manager" },
    { value: "Visual merchandiser" },
    { value: "Volunteer organiser" },
    { value: "Waiting staff" },
    { value: "Wardrobe assistant" },
    { value: "Warehouse manager" },
    { value: "Warehouse worker" },
    { value: "Waste management officer" },
    { value: "Waste plant manager" },
    { value: "Watch or clock repairer" },
    { value: "Water network operative" },
    { value: "Water treatment worker" },
    { value: "Web content manager" },
    { value: "Web designer" },
    { value: "Web developer" },
    { value: "Web editor" },
    { value: "Wedding planner" },
    { value: "Weighbridge operator" },
    { value: "Welder" },
    { value: "Welfare rights officer" },
    { value: "Window cleaner" },
    { value: "Window fitter" },
    { value: "Windscreen fitter" },
    { value: "Wine merchant" },
    { value: "Wood machinist" },
    { value: "Workshop supervisor" },
    { value: "Writer" },
    { value: "Yard person" },
    { value: "Yoga teacher" },
    { value: "Yoga therapist" },
    { value: "Youth offending team officer" },
    { value: "Youth worker" },
    { value: "Zookeeper" },
    { value: "Zoologist" }

  ];

     // setup autocomplete function pulling from currencies[] array
     $('#autocomplete').autocomplete({
          lookup: currencies,
          onSelect: function (suggestion) {
               var thehtml = '<strong>Currency Name:</strong> ' + suggestion.value + ' <br> <strong>Symbol:</strong> ' + suggestion.data;
               $('#outputcontent').html(thehtml);
          }
     });

});
